### ISSUE TITLE
There is a problem 

### ISSUE THREAD

**Issue by ZGamerOficial** [onebone/ItemCloud#1]
The console show me:[Server thread/WARNING]: A plugin atemppted a deprecated to register CallbackTask(Callback#onebone\economytax\EconomyTax::onShedule)
[Server thread/WARNING]: A plugin atemppted a deprecated to register CallbackTask(Callback#onebone\itemcloud\MainClass::save) 
[Server thread/INFO]: [EconomyAPI] Checking for updates...it may be take some while.
[Server thread/WARNING]: [EconomyAPI] An exception during check-update has been detected.
Please fix this!thanks for your attention!

**Comment by onebone** [comment]
Fixed

**Comment by ZGamerOficial** [comment]
Thanks good joob onebone
