### ISSUE TITLE
ItemCloud 1.2 download command ignores quantity

### ISSUE THREAD

**Issue by BlindTail** [onebone/ItemCloud#2]
When you do a command like this:

/itemcloud download 4 5

Instead of downloading 5 cobblestone, it only downloads 1. It seems to always do 1 no matter what quantity is specified.

We have temporarily reverted to 1.1 which does not have this bug.

**Comment by onebone** [comment]
Sorry, I will submit 1.3 by today. (UTC +9)

**Comment by BlindTail** [comment]
Thank you! 1.3 works great!
